# Generated by Django 5.0.6 on 2026-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_area',
            field=models.CharField(default='Osaka', max_length=50, verbose_name='メインエリア'),
        ),
    ]
