# Generated by Django 5.0.6 on 2026-08-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_title', models.CharField(max_length=50, verbose_name='ルートタイトル')),
                ('route_description', models.TextField(verbose_name='ルート本文')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='経度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'ルート',
                'verbose_name_plural': 'ルート一覧',
                'db_table': 'routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.BigIntegerField(verbose_name='並び順')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_reports', to='reports.report', verbose_name='レポート')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_reports', to='routes.route', verbose_name='ルート')),
            ],
            options={
                'verbose_name': 'ルート・レポート',
                'verbose_name_plural': 'ルート・レポート一覧',
                'db_table': 'route_reports',
                'ordering': ['route', 'sequence_order'],
            },
        ),
    ]
