# Generated by Django 5.0.6 on 2026-08-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='タグ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
            ],
            options={
                'verbose_name': 'ルートタグ',
                'verbose_name_plural': 'ルートタグ一覧',
                'db_table': 'route_tags',
                'ordering': ['tag_name'],
            },
        ),
        migrations.RemoveField(
            model_name='route',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='longitude',
        ),
        migrations.CreateModel(
            name='RouteTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_taggings', to='routes.route', verbose_name='ルート')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_taggings', to='routes.routetag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'ルート・タグ',
                'verbose_name_plural': 'ルート・タグ一覧',
                'db_table': 'route_taggings',
                'ordering': ['route', 'tag'],
                'unique_together': {('route', 'tag')},
            },
        ),
    ]
