# Generated by Django 5.0.6 on 2026-08-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=50, verbose_name='レポートタイトル')),
                ('report_description', models.TextField(verbose_name='レポート本文')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='経度')),
                ('report_image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'レポート',
                'verbose_name_plural': 'レポート一覧',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_comment', models.TextField(verbose_name='レポートコメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report', verbose_name='レポート')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'レポートコメント',
                'verbose_name_plural': 'レポートコメント一覧',
                'db_table': 'report_comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
