# Generated by Django 5.0.6 on 2026-08-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='タグ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
            ],
            options={
                'verbose_name': 'レポートタグ',
                'verbose_name_plural': 'レポートタグ一覧',
                'db_table': 'report_tags',
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_taggings', to='reports.report', verbose_name='レポート')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_taggings', to='reports.reporttag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'レポート・タグ',
                'verbose_name_plural': 'レポート・タグ一覧',
                'db_table': 'report_taggings',
                'ordering': ['report', 'tag'],
                'unique_together': {('report', 'tag')},
            },
        ),
    ]
