# Generated by Django 5.0.6 on 2026-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reporttag_reporttagging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_title',
            field=models.CharField(max_length=60, verbose_name='レポートタイトル'),
        ),
    ]
